name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - uses: ncipollo/release-action@v1
      with:
        name: session
        artifacts: "target/release/session.exe"
        prerelease: true
        tag: "v0.0.1"
